### ISSUE TITLE
14.02.2022

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [AlimaKarimova/PragmatechFrontEndProject#1]
Salam. Ümid edirəm ki, vəziyyət yaxşıdır.🙂

Bəzi düzəldilməli olan məqamlar:
- CSS faylları "css" adlı qovluqda olsa daha yaxşı olar.
- Commit mesajlarına xüsusi diqqət yetirin. Məsələn, ilk hərf böyük hərflə başlamalıdır. Düzgün commit mesajı yazmaqla bağlı [**bu**](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali) məqalə faydalı ola bilər. 
- Yazdığınız kodları səliqəli yazmağa çalışın. Bunun üçün "Prettier - Code formatter" extensionundan istifadə edə bilərsiniz. Bu extension kodları avtomatik olaraq səliqəyə salır. 
- Qovluq və fayl strukturuna çox fikir verin.
- "workspace.code-workspace" faylını silə bilərsiniz.

Uğurlar sizə!✌

**Comment by AlimaKarimova** [comment]
Salam Nezrin xanim yeniden geribildirimlerinizi gormek xosdur.Dediyiniz meqamlari nezere alacam

Понедельник, 14 февраля 2022, 2:36 +03:00 от Nəzrin İsbəndiyarova ***@***.***>:
>Salam. Ümid edirəm ki, vəziyyət yaxşıdır.🙂
>Bəzi düzəldilməli olan məqamlar:
>*  CSS faylları "css" adlı qovluqda olsa daha yaxşı olar.
>*  Commit mesajlarına xüsusi diqqət yetirin. Məsələn, ilk hərf böyük hərflə başlamalıdır. Düzgün commit mesajı yazmaqla bağlı  bu məqalə faydalı ola bilər.
>*  Yazdığınız kodları səliqəli yazmağa çalışın. Bunun üçün "Prettier - Code formatter" extensionundan istifadə edə bilərsiniz. Bu extension kodları avtomatik olaraq səliqəyə salır.
>*  Qovluq və fayl strukturuna çox fikir verin.
>*  "workspace.code-workspace" faylını silə bilərsiniz.
>Uğurlar sizə!✌
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you are subscribed to this thread. Message ID:  <AlimaKarimova/PragmatechFrontEndProject/issues/1 @ github . com>

С уважением,
Sunny Way
***@***.***
