### ISSUE TITLE
Task haqqında 06.03.2022

### ISSUE THREAD

**Issue by Rovshen98** [AlimaKarimova/PragmatechFrontEndProject#4]
Keçən dəfəki issueda da bildirdiyim kimi css qoşulanda linki / belə işarə ilə başlamayın. öz cihazınızda problemsiz göstərsə belə başqa cihazlarda css-i tapmaya bilər. Xahiş edirəm nəzərə alasınız.

HTML fayllarını page adlı folderdə yerləşdirmisiniz. Amma templates adlı folderdə olmağı daha düzgündür

edit-feedback səhifəsi əladır heç bir problem yoxdur.
new-feedback səhifəsi əladır heç bir problem yoxdur
roadmap - rəy iconu və bəzi iconlar qoyulmayıb. Qutunun ən yuxarısındakı yazı yoxdur. bu xırda problemlər həll olunsa qalan hər şey yaxşıdır 
suggestions-empty - əladır. heç bir problem yoxdur
suggestions səhifəsi əladır heç bir problem yoxdur

**Comment by AlimaKarimova** [comment]
salam linkle bagli problem yasayiram her defe.Sizin dediyiniz qaydada papkanin adini gostermeden qosmaga calismisam.
Asagida gosterilenlerden yalniz birincisini qosanda mende duzgun gorunur qalan hallarda css fayli qosulmamis formada yalniz html gorunur.Sizce ne ile bagli ola biler? Vs codun ayarlarinda nese problem ola biler?
"/ProductFeedbackUI/css/roadmap.css" >
/css/roadmap.css
css/roadmap.css
/roadmap.css
roadmap.css
  
>Воскресенье, 6 марта 2022, 1:45 +04:00 от Rövşən Şahbazov ***@***.***>:
> 
> 
>Keçən dəfəki issueda da bildirdiyim kimi css qoşulanda linki / belə işarə ilə başlamayın. öz cihazınızda problemsiz göstərsə belə başqa cihazlarda css-i tapmaya bilər. Xahiş edirəm nəzərə alasınız.
>HTML fayllarını page adlı folderdə yerləşdirmisiniz. Amma templates adlı folderdə olmağı daha düzgündür
>edit-feedback səhifəsi əladır heç bir problem yoxdur.
>new-feedback səhifəsi əladır heç bir problem yoxdur
>roadmap - rəy iconu və bəzi iconlar qoyulmayıb. Qutunun ən yuxarısındakı yazı yoxdur. bu xırda problemlər həll olunsa qalan hər şey yaxşıdır
>suggestions-empty - əladır. heç bir problem yoxdur
>suggestions səhifəsi əladır heç bir problem yoxdur
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you are subscribed to this thread. Message ID:  <AlimaKarimova/PragmatechFrontEndProject/issues/4 @ github . com>
 
 
С уважением,
Sunny Way
***@***.***
